resource_types:
- name: myip-resource
  type: docker-image
  source:
    repository: mrbuk/myip-resource
    tag: latest

- name: dodns
  type: docker-image
  source:
    repository: mrbuk/dodns
    tag: latest-final

resources:
- name: myip
  type: myip-resource
  source:
    # default
    #uri: https://api.ipify.org
    # change to a local server for testing
    #uri: http://192.168.0.100:8080

- name: dodns
  type: git
  source:
    uri: https://github.com/mrbuk/dodns

jobs:

- name: update-dodns
  plan:
  - aggregate:
    - get: dodns
      trigger: false
    - get: myip
      trigger: true
  - task: update-dodns
    file: dodns/pipeline/tasks/update-dodns/task.yml
    params:
      domain: {{domain}}
      subdomain: {{subdomain}}
      apitoken: {{apitoken}}
