resource_types:
- name: dodns
  type: docker-image
  source:
    repository: mrbuk/dodns
    tag: latest-final

resources:
- name: dodns
  type: git
  source:
    uri: https://github.com/mrbuk/dodns

- name: schedule
  type: time
  source:
    interval: 30m
    start: "12:00 AM"
    stop: "11:59 PM"
    location: Europe/Berlin
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

jobs:

- name: update-dodns
  plan:
  - aggregate:
    - get: schedule
      trigger: true
    - get: dodns

  - task: update-dodns
    file: dodns/pipeline/tasks/update-dodns/task.yml
    params:
      domain: {{domain}}
      subdomain: {{subdomain}}
      apitoken: {{apitoken}}
