---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mrbuk/dodns

inputs:
- name: dodns

params:
  domain:
  subdomain:
  apitoken:

run:
  path: dodns/pipelines/tasks/update-dodns/task.sh
